### ISSUE TITLE
build: Python 3.7 build fails

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/docker-invenio#10]
```console
The command '/bin/sh -c curl https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz -O -J -L && tar xzf Python-3.7.0.tgz -C /usr/src/ && /usr/src/Python-3.7.0/configure --enable-optimizations --prefix=/usr/bin/python3 && make altinstall && ln -s /usr/bin/python3/bin/python3.7 /usr/bin/python3.7 && rm Python-3.7.0.tgz' returned a non-zero code: 2
```

More [here](https://hub.docker.com/r/inveniosoftware/centos7-python/builds/b3jkjzif6adsqzzypswv9bg/).

**Comment by lnielsen** [comment]
I would probably just disable 3.7 builds since also Celery is currently failing on python 3.7

**Comment by lnielsen** [comment]
For upcoming sprint: reinvestigate if there's an easy way to get Python 3.7 and 3.8 images.

**Comment by ppanero** [comment]
ius cdn has been decomissioned: https://github.com/iusrepo/announce/issues/18

**Comment by ppanero** [comment]
closed by https://github.com/inveniosoftware/docker-invenio/pull/31
