### ISSUE TITLE
Pipenv error during installation

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/docker-invenio#28]
The base inveniosoftware/centos7-python image has errors due to the recent pipenv release (2020-05-28), where `pipenv install --system` attempts to use a (non-existent) virtualenv Python instead of the system Python. See e.g. https://github.com/pypa/pipenv/issues/4315

```
Installing dependencies from Pipfile.lock (876ab0)…
Failed to load paths: /bin/sh: /root/.local/share/virtualenvs/src--FJPeFkS/bin/python: No such file or directory
```

Needs a version pin [here](https://github.com/inveniosoftware/docker-invenio/blob/master/python3.6/Dockerfile#L37)

**Comment by alexdutton** [comment]
I'll put a PR together for this now. Should be ready in the next hour at the latest :-)

**Comment by ppanero** [comment]
This is happening again with the python 3.7 docker image:

```
Step 4/11 : RUN pipenv install --deploy --system --pre
 ---> Running in a2f9f4141155
Installing dependencies from Pipfile.lock (c1cc3c)…
Failed to load paths: /bin/sh: /root/.local/share/virtualenvs/src--FJPeFkS/bin/python: No such file or directory

Output:
Failed to load paths: /bin/sh: /root/.local/share/virtualenvs/src--FJPeFkS/bin/python: No such file or directory

Output:
Failed to load paths: /bin/sh: /root/.local/share/virtualenvs/src--FJPeFkS/bin/python: No such file or directory

Output:
Ignoring appnope: markers 'sys_platform == "darwin"' don't match your environment
```

**Comment by ppanero** [comment]
Happening also in `Python 3.6`

**Comment by alexdutton** [comment]
I'm going to have another look at this now :-)

**Comment by alexdutton** [comment]
Looks like this was fixed in https://github.com/pypa/pipenv/commit/cce026efbf6abf8b69b3c2051adb5afd30c8223d on the fourth of June. The most recent pipenv release was two days earlier, so we're still waiting for the fix to be on PyPI.

We could try https://github.com/pypa/pipenv/issues/4337#issuecomment-647931997, or just wait, as the error message does seem to be harmless.

**Comment by ppanero** [comment]
@alexsdutton thanks for checking. Is there a date for release? Could you pin it back again in a PR 😄 (sorry for my part on that...)
