### ISSUE TITLE
Webhooks and cron

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/docker-invenio#62]
- [x] Prototype a webhooks mapper service that will transform a webhook payload, received from Harbor (see [doc here](https://goharbor.io/docs/2.2.0/working-with-projects/project-configuration/configure-webhooks/)), to a version understood by the configured received (e.g. Discord, see [doc here](https://discord.com/developers/docs/resources/webhook#webhook-object-example-incoming-webhook)).
- [x] Create a repo to host the code, with tests, and deploy.
- [x] Implement some HTTP request that will maintain this GitHub repo crons active, so that the Docker image can be repeatedly built. Eventually, this can be probably done in CERN GitLab.

duplicate of https://github.com/inveniosoftware/docker-invenio/issues/64

**Comment by avivace** [comment]
https://github.com/inveniosoftware/alertabot is now up and deployed on OpenShift. Further issues to work on are described here https://github.com/inveniosoftware/alertabot/issues/1

**Comment by avivace** [comment]
Last point (cron) was moved in https://github.com/inveniosoftware/docker-invenio/issues/72
